# Generated by Django 5.2.6 on 2025-10-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_created_at_profile_email_profile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='realname',
        ),
    ]
