# Generated by Django 5.2.6 on 2025-09-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_artist_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
