# Generated by Django 5.2.6 on 2025-10-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_tag_options_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
